version: "2"

networks:
  operations-network:
    driver: bridge

services:
  mysql:
    image: mysql:5.6
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
      - ./data/mysql:/var/lib/mysql    
    networks:
      - operations-network  
  jira:
    image: cptactionhank/atlassian-jira:latest
    ports:
      - "8081:8080"
    volumes:
      - ./data/jira:/var/atlassian/jira
    networks:
      - operations-network
  bitbucket-server:
    image: dunkelfrosch/bitbucket
    ports:
      - "8082:7990"
      - "7999:7999"
    volumes:
      - ./data/bitbucket-server:/var/atlassian/application-data/bitbucket
    networks:
      - operations-network
  confluence-server:
    image: atlassian/confluence-server
    ports:
      - "8083:8090"
    volumes:
      - ./data/confluence-server:/var/atlassian/application-data/confluence
    networks:
      - operations-network