CREATE DATABASE IF NOT EXISTS jira CHARACTER SET utf8 COLLATE utf8_bin;
CREATE DATABASE IF NOT EXISTS bitbucket CHARACTER SET utf8 COLLATE utf8_bin;
CREATE DATABASE IF NOT EXISTS confluence CHARACTER SET utf8 COLLATE utf8_bin;